trigger:
  branches:
    include:
    - main
  paths:
    include:
    - frontend/*
    - backend/*

pr:
  branches:
    include:
    - main
  paths:
    include:
    - frontend/*
    - backend/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  NODE_VERSION: '18'
  FRONTEND_DIR: 'frontend'
  BACKEND_DIR: 'backend'
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: 'Build and Test'
  jobs:
  - job: BuildAndTest
    displayName: 'Build and Test'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: $(NODE_VERSION)
      displayName: 'Install Node.js'
    
    - script: |
        cd $(FRONTEND_DIR)
        npm ci
      displayName: 'Install Frontend Dependencies'
    
    - script: |
        cd $(FRONTEND_DIR)
        npm run build
      displayName: 'Build Frontend'
    
    - script: |
        cd $(BACKEND_DIR)
        npm ci
      displayName: 'Install Backend Dependencies'
    
    - script: |
        cd $(BACKEND_DIR)
        npm test || echo "No tests configured"
      displayName: 'Test Backend'
    
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(FRONTEND_DIR)/dist'
        artifactName: 'frontend-dist'
      displayName: 'Publish Frontend Artifacts'
    
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(BACKEND_DIR)'
        artifactName: 'backend-dist'
      displayName: 'Publish Backend Artifacts'

- stage: DeployStaging
  displayName: 'Deploy to Staging'
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - deployment: DeployFrontendStaging
    displayName: 'Deploy Frontend to Staging'
    environment: 'staging'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: frontend-dist
          
          - task: NodeTool@0
            inputs:
              versionSpec: $(NODE_VERSION)
            displayName: 'Install Node.js'
          
          - script: |
              npm install -g vercel
              cd $(Pipeline.Workspace)/frontend-dist
              vercel --token $(VERCEL_TOKEN)
            displayName: 'Deploy Frontend to Staging'
            env:
              VERCEL_TOKEN: $(VERCEL_TOKEN)

  - deployment: DeployBackendStaging
    displayName: 'Deploy Backend to Staging'
    environment: 'staging'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: backend-dist
          
          - task: NodeTool@0
            inputs:
              versionSpec: $(NODE_VERSION)
            displayName: 'Install Node.js'
          
          - script: |
              npm install -g @railway/cli
              cd $(Pipeline.Workspace)/backend-dist
              railway login --token $(RAILWAY_TOKEN)
              railway up
            displayName: 'Deploy Backend to Staging'
            env:
              RAILWAY_TOKEN: $(RAILWAY_TOKEN)

- stage: DeployProduction
  displayName: 'Deploy to Production'
  dependsOn: DeployStaging
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - deployment: DeployFrontendProduction
    displayName: 'Deploy Frontend to Production'
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: frontend-dist
          
          - task: NodeTool@0
            inputs:
              versionSpec: $(NODE_VERSION)
            displayName: 'Install Node.js'
          
          - script: |
              npm install -g vercel
              cd $(Pipeline.Workspace)/frontend-dist
              vercel --prod --token $(VERCEL_TOKEN)
            displayName: 'Deploy Frontend to Production'
            env:
              VERCEL_TOKEN: $(VERCEL_TOKEN)

  - deployment: DeployBackendProduction
    displayName: 'Deploy Backend to Production'
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: backend-dist
          
          - task: NodeTool@0
            inputs:
              versionSpec: $(NODE_VERSION)
            displayName: 'Install Node.js'
          
          - script: |
              npm install -g @railway/cli
              cd $(Pipeline.Workspace)/backend-dist
              railway login --token $(RAILWAY_TOKEN)
              railway up
            displayName: 'Deploy Backend to Production'
            env:
              RAILWAY_TOKEN: $(RAILWAY_TOKEN) 