version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - cd frontend && npm ci
      - cd ../backend && npm ci

  pre_build:
    commands:
      - echo Starting pre-build phase...
      - echo Logging in to Amazon ECR...
      - aws --version

  build:
    commands:
      - echo Build started on `date`
      - echo Building frontend...
      - cd frontend && npm run build
      - echo Building backend...
      - cd ../backend && npm test || echo "No tests configured"

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Deploying to production...

artifacts:
  files:
    - frontend/dist/**/*
    - backend/**/*
    - appspec.yml
    - scripts/**/*
  discard-paths: no
  base-directory: .

cache:
  paths:
    - 'frontend/node_modules/**/*'
    - 'backend/node_modules/**/*' 