steps:
  # Build frontend
  - name: 'node:18'
    entrypoint: npm
    args: ['ci']
    dir: 'frontend'
    id: 'install-frontend-deps'

  - name: 'node:18'
    entrypoint: npm
    args: ['run', 'build']
    dir: 'frontend'
    id: 'build-frontend'
    waitFor: ['install-frontend-deps']

  # Build backend
  - name: 'node:18'
    entrypoint: npm
    args: ['ci']
    dir: 'backend'
    id: 'install-backend-deps'

  - name: 'node:18'
    entrypoint: npm
    args: ['test']
    dir: 'backend'
    id: 'test-backend'
    waitFor: ['install-backend-deps']

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'wash-the-world-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/frontend:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
    id: 'deploy-frontend'
    waitFor: ['build-frontend']

  # Deploy backend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'wash-the-world-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/backend:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
    id: 'deploy-backend'
    waitFor: ['test-backend']

images:
  - 'gcr.io/$PROJECT_ID/frontend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/backend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1200s' 