services:
  - type: web
    name: wash-the-world-backend
    env: node
    buildCommand: npm install
    startCommand: node src/index-simple.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: CORS_ORIGIN
        value: https://your-frontend-domain.com
    healthCheckPath: /health
    autoDeploy: true 