version: 2.1

orbs:
  node: circleci/node@5.1.0
  aws-s3: circleci/aws-s3@4.0.0

jobs:
  build:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          app-dir: ./frontend
      - run:
          name: Build Frontend
          command: |
            cd frontend
            npm run build
      - persist_to_workspace:
          root: .
          paths:
            - frontend/dist

  deploy-frontend:
    docker:
      - image: cimg/aws-cli:3.0
    steps:
      - attach_workspace:
          at: .
      - aws-s3/sync:
          from: frontend/dist
          to: 's3://wash-the-world-frontend'
          arguments: |
            --delete
            --cache-control max-age=31536000
      - run:
          name: Invalidate CloudFront
          command: |
            aws cloudfront create-invalidation \
              --distribution-id $CLOUDFRONT_DISTRIBUTION_ID \
              --paths "/*"

  deploy-backend:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          app-dir: ./backend
      - run:
          name: Deploy to Railway
          command: |
            npm install -g @railway/cli
            railway login --token $RAILWAY_TOKEN
            railway up

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy-frontend:
          requires:
            - build
          filters:
            branches:
              only: main
      - deploy-backend:
          requires:
            - build
          filters:
            branches:
              only: main 